name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou la branche que tu utilises pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utiliser la dernière version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Utiliser la dernière version
        with:
          node-version: '22'  # ou la version de Node.js que tu utilises

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/attribute-validation-tool-front/"

      - name: Restart Nginx
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"
